networks:
  dns_vpn:
    name: "dns_vpn"
    ipam:
      config:
        - subnet: 10.8.1.0/24
          gateway: 10.8.1.1

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      # / Change the Web UI Password:
      FTLCONF_webserver_api_password: "dlmew2drezlx_5rub8#ubU6r@NajlSt6y9Xiza0i"
      TZ: "America/Lima"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "10.8.1.3#5053"
    volumes:
      - './pihole:/etc/pihole'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5051:80/tcp"
      - "5052:443/tcp"
    restart: unless-stopped
    networks:
      dns_vpn:
        ipv4_address: 10.8.1.2

  unbound: 
    image: mvance/unbound-rpi:latest # remember to change this if you're using rpi
    container_name: unbound
    hostname: unbound
    volumes:
      - './unbound:/opt/unbound/etc/unbound'
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    healthcheck:
      test: ["NONE"]
    restart: unless-stopped
    networks:
      dns_vpn: 
        ipv4_address: 10.8.1.3

  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    hostname: wireguard
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=joako-selfhost.ddns.net  #no-ip

      # ⚠️ Change the Web UI Password:
      - PASSWORD_HASH=$$2a$$12$$ba9zJZwnN7eXjV.PweT63e5BRjncRz/ZLZeTytoZ.KvzOZvd5Pgeu

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.2
      - WG_DEFAULT_ADDRESS=10.8.0.x
    volumes:
      - './wireguard:/etc/wireguard'
    ports:
      - "5054:51820/udp" #port forwarding
      - "5055:51821/tcp" #web console
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      dns_vpn:
        ipv4_address: 10.8.1.4
