services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: networking-NPM
    hostname: nginx-proxy-manager
    ports:
      # These ports are in format <host-port>:<container-port>
      - '9000:81' # Admin Web Port
      - '9001:80' # Public HTTP Port
      - '9002:443' # Public HTTPS Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
    volumes:
      - ./proxy-manager/data:/data
      - ./proxy-manager/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    restart: unless-stopped
    networks:
      main_network:

  noip-duc:
    image: noipcom/noip-duc:3.2.0
    container_name: networking-noip-duc
    hostname: noip-duc
    environment:
      - NOIP_USERNAME=${NOIP_USERNAME}
      - NOIP_PASSWORD=${NOIP_PASSWORD}
      - NOIP_HOSTNAMES=${NOIP_HOSTNAMES}
    restart: unless-stopped
    profiles:
        - skip
    networks:
      main_network:

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: networking-cloudflare-ddns
    hostname: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./cloudflare/cloudflare-ddns-config.json:/config.json
    restart: unless-stopped
    network_mode: "host"

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: networking-cloudfare-tunnel
    hostname: cloudfare-tunnel
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      main_network:

networks:
  main_network:
    external: true
