networks:
  main_network:
    external: true

services:
  homepage:
    image: nginx:alpine
    container_name: miscellaneous-homepage
    hostname: homepage
    environment:
      TZ: "America/Lima"
    ports:
      - "10011:80"
    volumes:
      - "./homepage:/usr/share/nginx/html:ro"
    restart: unless-stopped
    networks:
      main_network:
          
  snippet-box:
    image: pawelmalak/snippet-box:arm
    container_name: miscellaneous-snippets
    hostname: snippet-box
    environment:
      TZ: "America/Lima"
    ports:
      - "10012:5000"
    volumes:
      - "./snippet-box:/app/data"
    restart: unless-stopped
    networks:
      main_network:

  composerize:
    image: oaklight/composerize:latest
    container_name: miscellaneous-composerize
    hostname: composerize
    ports:
      - "10013:80"
    restart: unless-stopped
    networks:
      main_network:

  paperless-broker:
    image: docker.io/library/redis:7
    container_name: miscellaneous-paperless-broker
    hostname: paperless-broker
    volumes:
      - ./paperless/redisdata:/data
    restart: unless-stopped
    networks:
      main_network:

  paperless-webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: miscellaneous-paperless-ws
    hostname: paperless-ws
    depends_on:
      - paperless-broker
    ports:
      - "10015:8000"
    volumes:
      - ./paperless/data:/usr/src/paperless/data
      - ./paperless/media:/usr/src/paperless/media
      - ./paperless/export:/usr/src/paperless/export
      - ./paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_URL: https://paperless.joakolabs.com
    restart: unless-stopped
    networks:
      main_network:
