services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    hostname: proxy-manager
    ports:
      # These ports are in format <host-port>:<container-port>
      - '9000:81' # Admin Web Port
      - '9001:80' # Public HTTP Port
      - '9002:443' # Public HTTPS Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      INITIAL_ADMIN_EMAIL: "joaquinifloresp@gmail.com"
      INITIAL_ADMIN_PASSWORD: "cZ2*6&4$&MY2%3jwkLP7ogdy$P56Gqn8d@8w"
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped


networks:
  proxy-manager:
    name: "proxy-manager"
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.5.0/30
          gateway: 10.8.5.1
