networks:
  tools:
    name: "tools"
    ipam:
      config:
        - subnet: 10.8.4.0/24
          gateway: 10.8.4.1

services:
  composerize:
    image: oaklight/composerize:latest
    container_name: tools-composerize
    hostname: composerize
    ports:
      - "8050:80"
    restart: unless-stopped
    networks:
      tools:
        ipv4_address: 10.8.4.2
          
  homepage:
    image: nginx:alpine
    container_name: tools-homepage
    hostname: homepage
    environment:
      TZ: "America/Lima"
    ports:
      - "80:80"
    volumes:
      - "./www:/usr/share/nginx/html:ro"
    restart: unless-stopped
    networks:
      tools:
        ipv4_address: 10.8.4.3
