services:
  sui:
    image: nginx:alpine
    ports:
      - "30000:80"
    volumes:
      - "./sui-master:/usr/share/nginx/html:ro"
    networks:
      test:
 
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 30001:3000
    volumes:
      - ./homepage/config:/app/config # Make sure your local config directory exists
      - ./homepage/public:/app/public
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev,pi.local:30001 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    networks:
      test:

networks:
  test:
    name: "test"
    ipam:
      config:
        - subnet: 10.8.3.0/24
          gateway: 10.8.3.1
