services:
  sui:
    image: nginx:alpine
    ports:
      - "30000:80"
    volumes:
      - "./sui-master:/usr/share/nginx/html:ro"
    networks:
      test_network:
 
networks:
  test_network:
    name: "test_network"
    ipam:
      config:
        - subnet: 10.8.3.0/24
          gateway: 10.8.3.1
